//===============================================================================
// Genereate maximal length Negative Avoiding Sequences (NAS). When n is odd
// they correspond to a k-suffix language, which can be generated by adding
// a weight constraint and additional test to the FKM.  When n is even,
// Lempel's lift is applie to an NAS of order n-1; additional cycle are joined in.
//
// PROGRAMMED BY: Joe Sawada -- 2026
//===============================================================================
#include<stdio.h>
#include<math.h>

int n_orig,n,k;
int a[100],lempel;        // Generates the modified FKM
int aa[100],lempel2;      // For adding in the 2^n cycles in the even case
int ITERATION,ITERS_TIL_PUNCTURE,FIRST;
long long int total=0;

//===============================================
void PrintSym(int x) {
    if (x < 10) printf("%d", x);
    else printf("%c", 'A' + (x -10));
    total++;
}
//===============================================
// Apply Lempel and add an offset to the output
//===============================================
void Print2(int p, int offset)  {
    
    for (int i=1; i<=p; i++)  {
        lempel2 = (lempel2 + aa[i]) % 2;
        if (lempel2 == 0) PrintSym(offset);
        else PrintSym(offset + k/2);
    }
}
//============================================
// FKM recursive necklace generation in binary
//============================================
void FKM2(int t, int p, int offset) {

    if (t > n) {
        if (n%p == 0) Print2(p,offset);
        return;
    }
    aa[t] = aa[t-p]; FKM2(t+1,p,offset);
    if (aa[t] == 0) {
        aa[t] = 1;
        FKM2(t+1,t,offset);
    }
}
//===============================================
int GCD(int a, int b) {
    
    if (b == 0) return a;
    return GCD(b, a % b);
}
//===============================================
void Print(int p)  {
    int next_symbol;
    
    // EVEN CASE: Apply Lempel to the NAS of smaller order
    if (n_orig % 2 == 0) {
        for (int i=1; i<=p; i++)  {
            
            // Last symbol in the underlying NAS (the symbol k-1)
            if (p == 1 && a[i] == k-1) {
                if (ITERATION == 1) {
                    next_symbol = (lempel + a[i]) % k;
                    ITERS_TIL_PUNCTURE = k / GCD(k,next_symbol);
                }
                if (ITERATION % ITERS_TIL_PUNCTURE == 0) return;   // Puncture
            }
            
            lempel = (lempel + a[i]) % k;
            PrintSym(lempel);
        }
    }
    // ODD CASE: Print out the Lyndon prefix of the necklace
    else {
        for (int i=1; i<=p; i++) PrintSym(a[i]);
    }
}
//=======================================================
// Compute the necklace rep of b[] and store it in neck[]
//=======================================================
void GetNecklace(int b[], int neck[])  {
    int j,t,p;

    for (j=1; j<=n; j++) neck[n+j] = neck[j] = b[j]; // Concatenation b together to get neck
    
    j=t=p=1;
    do {
        t = t + p * ((j-t)/p);
        j = t + 1;
        p = 1;
        while (j <= 2*n && neck[j-p] <= neck[j]) {
            if (neck[j-p] < neck[j]) p = j-t+1;
            j++;
        }
    } while (p * ((j-t)/p) < n);
    
    for (j=1; j<=n; j++) neck[j] = neck[j+t-1];     // Move necklace to front of neck[]
}
//===============================================
// Test if necklace is smaller than its negative
//===============================================
int SmallerThanNeg()  {
    int i, b[100], neck[200];
    
    for (i=1; i<=n; i++) b[i] = (k - a[i]) % k;     // The negative
    GetNecklace(b,neck);     // Convert b to its necklace rep
    for (i=1; i<=n; i++) {
        if (a[i] < neck[i]) return 1;
        if (a[i] > neck[i]) return 0;
    }
    return 0;
}
//=====================================================================
// FKM recursive necklace generation, where w = double the pseudoweight
//=====================================================================
void FKM(int t, int p, int w) {
    int j,x;

    if ((n-t+1)*2*(k-1) + w < k*n) return;  // Dead end: cannot obtain required pseudoweight
    if (t > n) {
        if (n%p == 0 && (w > k*n || SmallerThanNeg())) Print(p);
        return;
    }
    for (j = a[t-p]; j<k; j++) {
        a[t] = j;
        if (j == 0) x = k;
        else x = 2*j;
        if (j == a[t-p]) FKM(t+1, p, w+x);
        else FKM(t+1, t, w+x);
    }
}
//===============================================
int main() {
    
	printf("Enter n k: ");  scanf("%d %d", &n_orig, &k);
 
    //--------------------------------------------
    // SPECIAL CASE for n_orig =2
    if (n_orig == 2) {
        
        // k EVEN -- Join (k/2 - 1) cycles eg. k=8 (77 1615141312 10) + (66 252423 20) + (55 34 30)
        if (k%2 == 0) {
            for (int i=1; i<=k/2-1; i++) {
                PrintSym(k-i); PrintSym(k-i);
                for (int j=i+1; j<=k-i-1; j++) { PrintSym(i); PrintSym(j); }
                PrintSym(i); PrintSym(0);
            }
        }
        
        // k ODD  -- Join smaller cycles, tricky if gcd(diff,i) > 1 
        // e.g. k=9 (012345678) (024681357) (036) (147) (258) (048372615) (1) (2) (3) (4)
        if (k%2 == 1) {
            for (int j=0; j<k; j++) {  // Join cycles to main cycle 0123...
                PrintSym(j);
                if (j > 0 && j <= k/2) PrintSym(j); // Extra symbol for 11,22, etc.
                for (int i=2; i <= k/2; i++) {      // i = difference between successive symbols
                    int g = GCD(i,k);
                    if (j < g) {
                        for (int t=1; t<=k/g; t++)  PrintSym( (j+(i*t)) % k);  // Join cycles ending with j
                    }
                }
            }
        }
    }
    //--------------------------------------------
    // EVEN CASE
    if (n_orig % 2 == 0 && n_orig > 2) {
        n = n_orig-1;
        a[0] = lempel = 0;
        for (ITERATION=1; ITERATION<=k; ITERATION++) {

            if (lempel > 0 && lempel <= (k-1)/2) {
                // Add symbols 0 < x < k/2 to include the strings [x,x,x,...x]
                if (k%2 == 1) PrintSym(lempel);
                
                // Add (k/2 - 1) cycles of length 2^n when k is even
                if (k%2 == 0)  {
                    aa[0] = lempel2 = 0;
                    printf("\n"); FKM2(1,1,lempel); printf("\n");
                }
            }
            
            FKM(1,1,0);  // Iterate through order n-1 NAS k times
        }
        for (int i=k/ITERS_TIL_PUNCTURE-1; i>=0; i--) PrintSym(i);  // JOIN PUNCTURED CYCLE ...3210.
    }
    //--------------------------------------------
    // ODD CASE
    if (n_orig % 2 == 1) {
        n = n_orig;
        a[0] = 0;
        FKM(1,1,0);
    }
    //--------------------------------------------
    printf("\nLength = %lld \n", total);
    if (k%2 == 1) printf("Expected = %ld \n", (long int) (pow(k,n_orig)-1)/2);
    if (k%2 == 0) printf("Expected = %ld \n", (long int) (pow(k,n_orig)-pow(2,n_orig))/2);
}
